apiVersion: v1
kind: Secret
metadata:
  name: weather-secret
type: Opaque
data:
  POSTGRES_USER: d2VhdGhlcnVzZXI=
  POSTGRES_PASSWORD: d2VhdGhlcnBhc3M=
  OPENWEATHER_API_KEY: M2E4NDQ4YTcyNTJlZjc0YjlhYzU1Mzc0NmI3ZTQyMWY=
